Do not load mermaid script from an external server
Enalean/tuleap-documentation-en pull request #1121
Opened 2023-02-09 11:13 UTC by LeSuisse

It gets blocked by our CSPs anyway and outside the security concern of loading a non pinned script this is unlikely to be legal under European laws.

Took the easiest way here and the graphs are now generated during the build. It also avoid loading 800KB+ of JS on every page.

2023-02-09 13:15 UTC, nterray requested changes

2023-02-09 13:15 UTC, nterray commented on .github/workflows/CI.yml
> -          pip install -r requirements.txt
Do we still need this file?

2023-02-09 13:24 UTC, LeSuisse commented on .github/workflows/CI.yml
> -          pip install -r requirements.txt
No because our build system does need it anymore. I did not wanted to mix the removal and the mermaid stuff

2023-02-10 08:35 UTC, nterray approved these changes

2023-02-10 08:36 UTC, merged