Refactor docker install doc
Enalean/tuleap-documentation-en pull request #1252
Opened 2023-08-28 13:58 UTC by fkozmik

The goal here is to have a documentation a bit more streamlined, as was the step by step version a while ago. 
I took the opportunity to add some more information about compose as well (for TEE).

2023-09-04 07:29 UTC, LeSuisse requested changes

2023-09-04 07:29 UTC, LeSuisse commented on languages/en/installation-guide/docker/docker_compose.rst
> +By default, we spawned a `mailhog <https://github.com/mailhog/MailHog>`_ image
It would be preferable to completely drop mailhog from the compose file. It is basically unmaintained for 3 years.

2023-09-04 07:29 UTC, LeSuisse commented on languages/en/installation-guide/docker/docker_compose.rst
> +          - db-data:/var/lib/mysql
If you rename that you should also rename L92.

2023-09-04 07:29 UTC, LeSuisse commented on languages/en/installation-guide/docker/docker_compose.rst
> +    REDIS_FQDN=another strong password
Those are not password.

2023-09-04 07:29 UTC, LeSuisse commented on languages/en/installation-guide/docker/docker_compose.rst
> +        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
Why is this needed?

2023-09-04 07:29 UTC, LeSuisse commented on languages/en/installation-guide/docker/docker_compose.rst
> +You should add these variables in your ``.env`` file (along with the :ref:`aforementionned ones <env-variables>`):
```suggestion
You should add these variables in your ``.env`` file (along with the :ref:`aforementioned ones <env-variables>`):
```

2023-09-04 07:29 UTC, LeSuisse commented on languages/en/installation-guide/docker/docker_compose.rst
> +    docker constraints.
```suggestion
    The following section is meant for test purpose only. The databases (MySQL and Redis) are handled by Docker and it is not a recommend setup.
```

There is no "unless", it is not recommended.

2023-09-04 07:29 UTC, LeSuisse commented on languages/en/installation-guide/docker/docker_compose.rst
> +In a directory named ``tuleap-stack`` (be careful, with docker-compose, directory name matters) create a
Why does it matters here? There is nothing hardcoded to it as far as I can see.

2023-09-05 08:07 UTC, fkozmik commented on languages/en/installation-guide/docker/docker_compose.rst
> +        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
I believed it was best to spawn an RP directly into the stack. Your review made me realize that it should not be a "by default" setting, as well as it is not in fact necessary for Tuleap to function correctly.

2023-09-12 14:35 UTC, Hyzual requested changes
A lot of comments but don't despair, they are only details :) Thanks for the work on this doc !

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_standalone.rst
> +For anything but tests you should have a dedicated MySQL (**version 8.0**) and Redis (last stable recommended) databases.
```suggestion
For anything but tests, you should have a dedicated MySQL (**version 8.0**) and Redis (last stable recommended) databases.
```

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_standalone.rst
> +For future runs you don't need to pass all the environments:
```suggestion
For future runs you don't need to pass all the environment variables:
```

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_standalone.rst
> +When running, the container exposes the following ports:
suggestion: it feels like L100-L104 would fit better after L17

To put it another way, it's weird to see this at the end of the "TEE" paragraph, it applies to both images, so it belongs at the beginning with the explanation of the data volume and the env vars.

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_standalone.rst
> +        -v tuleap-data:/data
question: should we match the fake path used above for TCE ?

I'm not sure if it's intended to be different. If it isn't, we could reuse the line `-v /srv/path/to/data:/data`

Same below at L97

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +.. code-block::
```suggestion
.. code-block:: ini
```

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +* ``TULEAP_FQDN`` is the full name of the machine you are going to run Tuleap on. As we saw in pre-requisite section, it should be the name of your docker host either from DNS or at very least define
```suggestion
* ``TULEAP_FQDN`` is the full name of the machine you are going to run Tuleap on. As we saw in pre-requisite section, it should be the name of your docker host either from DNS or at the very least defined in ``/etc/hosts`` (will resolve only locally).
```

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +Notes about passwords:
nitpick: this section would better fit in the images-configuration page

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +    SITE_ADMINISTRATOR_PASSWORD=and a third strong password
thought: Does it work with `=` in a password ? I remember having a hard time with an env file once because of a special character in a password. Might be nice to warn people about that (even though that's going above and beyond)

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +          - TULEAP_FQDN=${TULEAP_FQDN}
question: what happened to the `.env` file frome above ? It looks like we never use it. From the top of my head, the compose file needs an `environment_file:` property

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +        - TULEAP_FQDN=${TULEAP_FQDN}
question: same as above, are we using the `.env` file ? From what I can read, it seems not

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +The docker-compose file provided here is for general guidance and you should adapt to your environment.
```suggestion
The docker-compose file provided here is for general guidance and you should adapt it to your environment. 
```

2023-09-12 14:35 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +One of the main thing you will want to configure is a proper email relay.
```suggestion
One of the main things you will want to configure is a proper email relay.
```

2023-09-14 08:14 UTC, fkozmik commented on languages/en/installation-guide/docker/docker_compose.rst
> +          - TULEAP_FQDN=${TULEAP_FQDN}
AFAIK, the `env_file` property is there to use an environment file that is not stored on the root of the project. https://docs.docker.com/compose/environment-variables/set-environment-variables/

2023-09-14 08:14 UTC, fkozmik commented on languages/en/installation-guide/docker/docker_compose.rst
> +        - TULEAP_FQDN=${TULEAP_FQDN}
Same answer :)

2023-09-14 08:45 UTC, fkozmik commented on languages/en/installation-guide/docker/introduction.rst
>     images-configuration
You are right, I've added a small explaination about the images

2023-09-14 09:17 UTC, fkozmik commented on languages/en/installation-guide/docker/verify_images_authenticity.rst
> +We sign the Tuleap Enterprise Docker images each time we publish them. The images are signed using `cosign <https://github.com/sigstore/cosign>`_.
You are right, it doesn't need to be plural. We have only one TEE image that can be called by it's major release version tag, or by it's minor. Either way each time a new tag spawns it is signed so no need to be plural

2023-09-14 09:22 UTC, fkozmik commented on languages/en/installation-guide/docker/docker_standalone.rst
> +        -v tuleap-data:/data
You are right, there's no real need to use a docker volume in that case. 
In any way, if the clients know enough about docker they can choose to use docker volumes instead.

2023-09-14 09:32 UTC, fkozmik commented on languages/en/installation-guide/docker/docker_compose.rst
> +Notes about passwords:
Makes sense

2023-09-14 12:49 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +    SITE_ADMINISTRATOR_PASSWORD=and a third strong password
I did not know about the double quotes, thanks !

2023-09-14 12:49 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +          - TULEAP_FQDN=${TULEAP_FQDN}
Ok, I did not know about that. Thanks !

2023-09-14 12:49 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +    The following section is meant for test purpose only. The databases (MySQL and Redis) are handled by Docker and it is not a recommend setup.
```suggestion
    The following section is meant for test purpose only. The databases (MySQL and Redis) are handled by Docker and it is not a recommended setup.
```

2023-09-14 12:49 UTC, Hyzual commented on languages/en/installation-guide/docker/docker_compose.rst
> +        - TULEAP_FQDN=${TULEAP_FQDN}
Thanks

2023-09-14 12:49 UTC, Hyzual commented on languages/en/installation-guide/docker/intro_docker.rst
> +It allows you to not be bothered by different OS migrations and the like.
:+1:

2023-09-14 12:51 UTC, Hyzual approved these changes

2023-09-15 07:50 UTC, merged