Modification custom logo
Enalean/tuleap-documentation-en pull request #1331
Opened 2024-01-26 13:16 UTC by bpeytraud

In this modification the objective is to be more precise on the PNG part. I made two parts, one for the tuleap server and one for the docker. It’s more useful to do this than to have generic information on the PNG part. I explain in details how to add the two PNG files in the tuleap server and in the docker. I think it’s important to be clear on those points to facilitate the user in his attempt to have a new logo on his page.

2024-01-31 14:05 UTC, vaceletm requested changes

2024-01-31 14:05 UTC, vaceletm commented on languages/en/administration-guide/system-administration/customisations.rst
> +When this is done you can go exit the bash environment.
1. It should work with only one step if you use `cp -f` in the command bellow (that will override the target file)
2. I suggest that, instead of `name_of_directory`, you enfore ce name, for instance `/pictures`, this way, it's easy for admin to copy/paste, it's one less thing to change
3. You don't need to to precise what `alpine` is

2024-01-31 14:05 UTC, vaceletm commented on languages/en/administration-guide/system-administration/customisations.rst
> +``docker run -v directory_files/:name_of_directory -v name_volume:/tuleap-data -t -i cp name_of_directory/organization_logo.png /tuleap-data/var/lib/tuleap/images``
1. Please add `--rm` to  `docker run`  arguments, you don't need to keep the container used for cp
2. you don't need `-t` and `-i` here because there is no interactions
3. I would suggest to copy using `organisation_logo*.png` so it copies all the files at once

2024-01-31 14:05 UTC, vaceletm commented on languages/en/administration-guide/system-administration/customisations.rst
> +Now you can start docker with : ``docker compose up -d``
A restart of web container should be enough

2024-02-01 08:54 UTC, bpeytraud commented on languages/en/administration-guide/system-administration/customisations.rst
> +When this is done you can go exit the bash environment.
I understand your point. I will do one command, but in other hand I will precise what the command does.

2024-02-01 09:00 UTC, bpeytraud commented on languages/en/administration-guide/system-administration/customisations.rst
> +``docker run -v directory_files/:name_of_directory -v name_volume:/tuleap-data -t -i cp name_of_directory/organization_logo.png /tuleap-data/var/lib/tuleap/images``
The review above is a part of this review.

2024-09-03 07:53 UTC, closed without merging