Doc: One page for install tuleap tee/tce
Enalean/tuleap-documentation-en pull request #1422
Opened 2024-06-05 09:38 UTC by bpeytraud

This commit is to facilitate the user with the installation of Tuleap Enterprise or Community This commit is part of the request #38276

2024-06-05 12:32 UTC, vaceletm commented
I would rename `languages/en/installation-guide/step-by-step/install-packages-tee-tce.rst` into `languages/en/installation-guide/step-by-step/install-packages.rst` that makes more sense given the new content

2024-06-05 12:36 UTC, vaceletm requested changes

2024-06-05 12:36 UTC, vaceletm commented on languages/en/installation-guide/step-by-step/install-packages-tee-tce.rst
> -.. _tuleap_installation_install_packages_tee:
I don't get the point of removing this reference (and adding _tuleap_enterprise_edition below). Wouldn't be more consistent to move this anchor near "Tuleap Enterprise Edition"  (L14) ?

2024-06-05 12:36 UTC, vaceletm commented on languages/en/installation-guide/step-by-step/install-packages-tee-tce.rst
> +Install packages - Tuleap TEE or TCE
```suggestion
Install packages
```

2024-06-05 12:36 UTC, vaceletm commented on languages/en/installation-guide/step-by-step/install-packages-tee-tce.rst
> +- `Tuleap Enterprise Edition`_
You should add a quick description of what each edition is + reference to Tuleap Enterprise Edition page

2024-06-07 12:49 UTC, sandrae approved these changes

2024-06-10 08:09 UTC, vaceletm commented on languages/en/installation-guide/step-by-step/install-packages-tee-tce.rst
> -.. _tuleap_installation_install_packages_tee:
Anchors are there so we can point directly to the part of the page that corresponds to the section. That's the whole point of anchors so they have to be near the corresponding section.

2024-06-10 08:11 UTC, vaceletm commented on languages/en/installation-guide/step-by-step/install-packages-tee-tce.rst
> +- `Tuleap Enterprise Edition`_
Yes it is the point here. We are doing those changes because people that want to install Tuleap don't get the difference beween TCE and TEE

2024-06-14 09:28 UTC, vaceletm requested changes

2024-06-14 09:28 UTC, vaceletm commented on languages/en/installation-guide/step-by-step/install-packages.rst
> +It can be installed on CentOs or Redhat servers and it represents the under development version of Tuleap.
```suggestion
`Tuleap Enterprise Edition <tuleap-enterprise>`_ is a special distribution of Tuleap crafted by `Enalean <https://enalean.com>`_ with more plugins and enhanced reliability.

Tuleap Community Edition is the development version of Tuleap with a limited set of plugins. 
```

2024-06-14 09:39 UTC, bpeytraud commented on languages/en/installation-guide/step-by-step/install-packages.rst
> +It can be installed on CentOs or Redhat servers and it represents the under development version of Tuleap.
Don't you want to put a link to on-premises more than enalean.com ?

2024-06-14 09:57 UTC, vaceletm commented on languages/en/installation-guide/step-by-step/install-packages.rst
> +It can be installed on CentOs or Redhat servers and it represents the under development version of Tuleap.
No, it's not clear at this stage that it's the right place to point out for TEE description.

2024-06-17 07:02 UTC, merged