Doc: "How-to" modification help page
Enalean/tuleap-documentation-en pull request #1424
Opened 2024-06-07 09:51 UTC by bpeytraud

This commit is a new "How-to" to help client to configure the help page.

2024-06-17 08:20 UTC, sandrae requested changes

2024-06-17 08:20 UTC, sandrae commented on languages/en/how-to.rst
> +   how-to/administration/help-configuration-page
rather "customise-help-page"

2024-06-17 08:20 UTC, sandrae commented on languages/en/how-to/administration/help-configuration-page.rst
> +Modification page help
How to customise your help page

2024-06-17 08:20 UTC, sandrae commented on languages/en/how-to/administration/help-configuration-page.rst
> +
You should add a small introduction indicating why Tuleap adminsitrators should customise this page

2024-06-17 08:20 UTC, sandrae commented on languages/en/how-to/administration/help-configuration-page.rst
> +To do so you need to go to ``/etc/tuleap/site-content/your_language/help``.
You need to have an SSH access on the server to do this.

2024-06-17 08:20 UTC, sandrae commented on languages/en/how-to/administration/help-configuration-page.rst
> +
Be more specific, for instance : For each language available on your platform...
And give the complete example :
cd /etc/...
ou
vi ....

2024-06-17 08:20 UTC, sandrae commented on languages/en/how-to/administration/help-configuration-page.rst
> +Now you can edit the file ``site.txt`` as wish.
Maybe give an example, with a fictive company

2024-06-17 09:18 UTC, bpeytraud commented on languages/en/how-to/administration/help-configuration-page.rst
> +To do so you need to go to ``/etc/tuleap/site-content/your_language/help``.
In the case of a Tuleap cloud, what will be the procedure because they don't have access to the server.

2024-06-19 07:47 UTC, sandrae commented on languages/en/how-to/administration/help-configuration-page.rst
> +To do so you need to go to ``/etc/tuleap/site-content/your_language/help``.
You're right. However, the process is the same. It's not the place to make a difference between OnPrem or Cloud.

2024-06-24 15:37 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +Here is an example of what you can do :
I was thinking of an html example with a fake email to contact  for instance.

2024-06-24 15:37 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +Introduction
No need of this subtitle

2024-06-24 15:37 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +You need to be an administrator of your server to do the modification.
You need to have an SSH access to the Tuleap server to customize this part

2024-06-24 15:37 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +In the bottom right of your tuleap page. You have a star or a question mark depending of the version that you are using.
The help page is accessible with :
- The star or question amrk at the bottom right...
- Throught this URL : https: //yourtuleapserver/help

2024-06-24 15:37 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +This page can be modified. For example, to put a link to ask a question to your support team.
We recommand to modify that page in order to ...

2024-06-25 08:24 UTC, bpeytraud commented on languages/en/how-to/administration/customise-help-page.rst
> +Here is an example of what you can do :
Do you want me to take the all html code of the help page with the modification. Or just the part of the modication I put in.

2024-06-25 12:29 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +Here is an example of what you can do :
Just a simple html example, with a fake email to contact, not necessarily all the existing default page.

2024-07-10 13:30 UTC, sandrae requested changes

2024-07-10 13:30 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +        <p> For all other inquiries use <a href="mailto:support_team@example.com">support_teamp@example.com</a></p>
team instead of teamp

2024-07-10 13:30 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
>  Depending of your language, you will not using the same help page.
You will have to define one help page per language used on your platform. 
For French use, vi /etc/tuleap/site-content/fr_FR/help/site.txt
For English use, ....
etc.

2024-07-10 13:30 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> +We recommand to modify that page in order to be able to ask a question to your support team.
To be removed, To be added in intro.

2024-07-10 13:30 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
>  This How-to is here to inform you how to customise your help page.
We recommand to customise the Tuleap Help page in order to help your end-users finding the support channels within your company.
Here is how to do it.

2024-07-18 14:05 UTC, sandrae requested changes

2024-07-18 14:05 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
>      * Throught this URL : ``https://yourtuleapserver/help``
Through

2024-07-18 14:05 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> -We recommand to modify that page in order to be able to ask a question to your support team.
to your company support team

2024-07-18 14:05 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
>  Now you can edit the file ``site.txt`` as wish.
as wished

2024-07-18 14:05 UTC, sandrae commented on languages/en/how-to/administration/customise-help-page.rst
> -        <p> For all other inquiries use <a href="mailto:support_team@example.com">support_teamp@example.com</a></p>
For all requests, use ...

2024-07-18 14:58 UTC, bpeytraud commented on languages/en/how-to/administration/customise-help-page.rst
> -We recommand to modify that page in order to be able to ask a question to your support team.
I deleted this line in my previous commit do you want to reintegrate it ?

2024-08-05 12:41 UTC, merged