doc: Add documentation about export mode in XTS widget
Enalean/tuleap-documentation-en pull request #1481
Opened 2024-08-09 10:13 UTC by Gashmob

Part of [story #39019 Switch mode in Cross tracker search widget](https://tuleap.net/plugins/tracker/?aid=39019)

2024-08-09 13:19 UTC, Hyzual commented on languages/en/user-guide/tql.rst
suggestion: could you please add a section about the API breaking change in the deployment guide ? Same thing as we did for release 15.10. It should explain that `return_format` is removed and that existing cross-tracker widgets have been updated and should keep functioning as before

2024-08-09 13:48 UTC, Hyzual requested changes

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
suggestion: L208 is now incorrect

> When you use a semantic, all selected trackers must have it configured and all fields linked to the semantic must be readable by the current user.

Now, it works if _at least one_ tracker has the semantic. Would you mind changing this paragraph ?

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
suggestion: L213 should include "Artifact id". L236 "Supported comparisons" should also include `@assigned_to` and `@id`

If you want, we can split the work on updating this. We did not update the doc after the changes on WHERE on previous releases, so we gotta do it now.

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
suggestion: L211 is incorrect too: it works if _at least one_ tracker has the field

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
suggestion: I don't think we mention filtering on duck-typed fields, this page only talks about semantics and always-there fields. We should probably explain that in XTS TQL we can also search on duck-typed fields, and explain what the rules for matching are

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
Perfect, thanks :+1:

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> +  You can follow advancement in the associated epic https://tuleap.net/plugins/tracker/?aid=37567
```suggestion
  You can follow advancement in `epic #37567 SuperTableau - Full TQL mode <https://tuleap.net/plugins/tracker/?aid=37567>`_
```

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> + * ``@submitted_on`` Artifact creation datetime
```suggestion
 * ``@submitted_on`` The creation date and time of the artifact.
```
To match L214

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> + * ``@last_update_date`` Artifact last update datetime
```suggestion
 * ``@last_update_date`` The date and time of the last change to the artifact.
```
To match L216

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> + * ``@submitted_by`` User who created the artifact
```suggestion
 * ``@submitted_by`` The user who first created the artifact.
```
To match L215

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> + * ``@last_update_by`` User who performed last update of the artifact
```suggestion
 * ``@last_update_by`` The user who made the last change to the artifact.
```
To match L217

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> +Fields short name
question: should we expand that part ? Maybe we can link back to the explanation of duck-typed fields we need to write 😅

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> + * ``@pretty_title`` It's equivalent to the Artifact column of classic Cross-tracker search widget (or the title of the artifact view).
praise: good explanation :+1:

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> + * ``@project.name``
```suggestion
 * ``@project.name`` The name and icon of the project that the artifact belongs to.
```

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> + * ``@tracker.name``
```suggestion
 * ``@tracker.name`` The name and color of the tracker the artifact belongs to.
```

2024-08-09 13:48 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> +To switch a widget to this mode, you should use the REST API ``PUT /cross_tracker_reports/{id}``. The body of your request should contains the key ``report_mode`` with the value ``expert``.
suggestion: not sure we want to explain that publicly in the doc just yet. Since "the paint is not dry" and it's still a tech preview... And besides, we will have to delete this sentence when the widget frontend does allow to switch through the web UI.
I suggest to remove this sentence. What do you think ?

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +To switch a widget to this mode, you should use the REST API ``PUT /cross_tracker_reports/{id}``. The body of your request should contains the key ``report_mode`` with the value ``expert``.
Ok, I agree

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> + * ``@tracker.name``
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> + * ``@project.name``
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> + * ``@last_update_by`` User who performed last update of the artifact
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> + * ``@submitted_by`` User who created the artifact
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> + * ``@last_update_date`` Artifact last update datetime
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> + * ``@submitted_on`` Artifact creation datetime
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +  You can follow advancement in the associated epic https://tuleap.net/plugins/tracker/?aid=37567
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
Done

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
It's already explained line 189

2024-08-09 14:27 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +Fields short name
Done

2024-08-09 15:09 UTC, Hyzual requested changes

2024-08-09 15:09 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> +Fields short name
With the link it's better, but there is actually a difference: for SELECT, date and datetime are compatible together...

2024-08-09 15:09 UTC, Hyzual commented on languages/en/user-guide/tql.rst
> +.. _tql_duck_typing:
```suggestion
.. _tql_duck_typing:

Searching on similar fields
'''''''''''''''''''''''''''
```

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
>   * ``@assigned_to``: the "Contributor/assignee"`` semantic. It behaves like a list and can have multiple values at a time (multiple users assigned to an artifact).
Done

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +.. _tql_duck_typing:
Done

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +When you use a semantic, at least one of selected trackers must have it configured and field linked to the semantic must be readable by the current user.
Done

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +If **none** of the trackers does not define the "Status" semantic, it will cause an error to be shown. The same is true for permissions: if **none** of the "Status" fields is not readable by the curr
Done

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +When you use a dynamic field, for at least one of selected trackers it must be added in the tracker and it must be readable by the current user.
Done

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
>    * "Last Updated Date": The date of the last change to the artifact.
Done

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +If **none** of the trackers does not have a "Last update date" field, it will cause an error to be shown. The same is true for permissions: if **none** of the "Last update date" fields is not readabl
Done

2024-08-12 06:56 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +  You can follow advancement in `epic #37567 SuperTableau - Full TQL mode <https://tuleap.net/plugins/tracker/?aid=37567>`
Strange syntax :thinking:. Done

2024-08-12 06:59 UTC, Gashmob commented on languages/en/user-guide/tql.rst
> +Fields short name
Done

2024-08-12 08:26 UTC, Hyzual approved these changes

2024-08-12 08:26 UTC, merged