doc: Split TQL documentation
Enalean/tuleap-documentation-en pull request #1527
Opened 2024-10-07 09:58 UTC by Gashmob

Separate part for TQL in reports and TQL in Cross-Tracker Search

2024-10-07 12:06 UTC, nterray requested changes

2024-10-07 12:06 UTC, nterray commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +TQL can be used in the Cross-Tracker Search widget, in the search area.
There are important information in User guide » Project management » Project dashboard » Portfolio about this widget (behavior of the widget, permissions, default query, …). We are starting here to detail the behavior of the widget in two different places. I fear that user can get lost, or that we will add an information that should be elsewhere… 
I have the feeling that we should move this section in Portfolio and put a link to it so that this documentation focus on TQL syntax and specificities...

2024-10-07 12:41 UTC, Hyzual commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +TQL ``SELECT`` syntax allows you to select on the same fields allowed for the condition plus some special fields:
good idea, done

2024-10-07 14:09 UTC, Hyzual reviewed
Note: I will squash the commits once approved

2024-10-07 14:21 UTC, robinsoc commented on languages/en/user-guide/tql/cross-tracker-search.rst
> + * ``@pretty_title`` It's equivalent to the Artifact column of classic Cross-tracker search widget (or the title of the artifact view).
suggestion: IMHO, users do not always know how it is displayed/formatted in the classic Cross-tracker search widget. 

What do you think about to explain how the value of the column is formatted ?
It would avoid the user to search elsewhere in the documentation on how it is formatted.

2024-10-07 14:52 UTC, nterray commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +.. important:: The query is too complex when it exceeds a limit. This limit is defined by Site Administrators on Site Administration > Tracker > Report.
Done

2024-10-07 14:54 UTC, nterray commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +You must provide 1 or 2 condition of different kind. If only the project condition is provided then it gets all trackers from corresponding projects.
Yes, thanks.

2024-10-07 14:56 UTC, nterray commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +Some examples you can take inspiration from:
Yes, I would add a dedicated section:
```suggestion
Examples
''''''''

Some examples you can take inspiration from:
```

2024-10-07 14:57 UTC, nterray commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +~~~~~~~~~~~~~~~~~~~~~~
It seems to be done. Thanks.

2024-10-07 14:59 UTC, nterray commented on languages/en/user-guide/project-admin.rst
> +The query uses the TQL language. You can find more information about the query format :ref:`here <xts>`.
nitpick: I would mention in "CSV Export" that it is not available in expert mode.

2024-10-07 15:07 UTC, nterray commented on languages/en/images/screenshots/tql/expert_query_xtracker_widget.png
nitpick: we now have two different screenshots for the same widget. Since maintenance of screenshot is a PITA, I would suggest to keep only one.

2024-10-07 15:08 UTC, nterray commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +TQL can be used in the Cross-Tracker Search widget, in the search area.
I think so, Thanks

2024-10-07 15:09 UTC, nterray requested changes
See @robinsoc comment and examples section.

2024-10-08 08:12 UTC, Hyzual commented on languages/en/images/screenshots/tql/expert_query_xtracker_widget.png
Which one is the other screenshot you refer to ? I agree on the maintenance of screenshots.

2024-10-08 08:12 UTC, Hyzual commented on languages/en/user-guide/tql/cross-tracker-search.rst
> + * ``@pretty_title`` It's equivalent to the Artifact column of classic Cross-tracker search widget (or the title of the artifact view).
You're right. Done, is it better ?

2024-10-08 08:13 UTC, Hyzual commented on languages/en/user-guide/project-admin.rst
> +The query uses the TQL language. You can find more information about the query format :ref:`here <xts>`.
Done

2024-10-08 13:31 UTC, robinsoc requested changes

2024-10-08 14:36 UTC, Hyzual commented on languages/en/user-guide/project-admin.rst
> +A widget "Cross-tracker search" enables you to do that.
Done

2024-10-08 14:36 UTC, Hyzual commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +There cannot be multiple conditions on  ``@project``. For example, the following query will be rejected: ``FROM @project.category = 'Type::Helpdesk' AND @project.name = 'foo'``). Similarly, there can
Indeed, done

2024-10-08 14:36 UTC, Hyzual commented on languages/en/user-guide/tql/cross-tracker-search.rst
> +To provide both conditions, you can use ``AND`` between them. There is no restriction for the order of the conditions. For example: ``FROM @project.category = 'Type::Helpdesk' AND @tracker.name = 're
Indeed, done

2024-10-08 14:36 UTC, Hyzual commented on languages/en/user-guide/tql/tracker-report.rst
> +Queries
I thought we had mentioned it here, but we did not. Good idea, I'll add it.

2024-10-08 16:04 UTC, nterray commented on languages/en/images/screenshots/tql/expert_query_xtracker_widget.png
The one in Project management » Project Dashboard » Cross-Tracker Search: /user-guide/project-admin.html#cross-tracker-search

2024-10-09 13:16 UTC, nterray commented on languages/en/images/screenshots/tql/expert_query_xtracker_widget.png
Thanks

2024-10-09 13:17 UTC, nterray approved these changes

2024-10-09 13:17 UTC, merged