docs: Explain that Expert mode is default in Cross-Tracker search
Enalean/tuleap-documentation-en pull request #1550
Opened 2024-11-12 16:58 UTC by Hyzual

part of story #40088 Expert mode is the new default for cross tracker search

2024-11-13 07:03 UTC, robinsoc requested changes

2024-11-13 07:03 UTC, robinsoc commented on languages/en/user-guide/project-admin.rst
> +The Cross-Tracker Search widget has a second mode called "Default mode" that allows you to select a list of trackers coming from different projects and to filter artifacts from those trackers accordi
suggestion: button => switch button 
if the user search a 'classic' button (like the `Search` or `Cancel` button), he might be a little confused

2024-11-13 07:03 UTC, robinsoc commented on languages/en/user-guide/project-admin.rst
> +If you can't read all trackers or all columns needed by the query, an error message will be displayed.
This part also concern the expert mode.
In the expert mode, an error is also displayed when no tracker can be read.

Maybe a copy/paste in the `Expert mode` part is enough

2024-11-13 07:03 UTC, robinsoc commented on languages/en/user-guide/project-admin.rst
> +After selecting trackers and/or entering a query, you will be able to Save the report. Once saved, all users who can access this dashboard will see the widget with your saved tracker selection and qu
This part also concern the expert mode.
By reading that here, the user can think he can save the report only in default mode 

Maybe a copy/paste in the Expert mode part is enough

2024-11-13 07:54 UTC, Gashmob requested changes

2024-11-13 07:54 UTC, Gashmob commented on languages/en/images/screenshots/widget/crosstracker-widget.png
question: Have you crushed the image?

2024-11-13 07:54 UTC, Gashmob commented on languages/en/user-guide/project-admin.rst
> +You can optionally write a query using :ref:`Tuleap Query Language <xts_default_mode>` If you don't write a query, it will by default search all "Open" artifacts in the selected projects. If you use
> the retrieved artifacts will match the query and not only the "Open" ones

This is confusing, what I understand reading this is that if I write a query I retrieve artifact matching it + "open" artifacts.

2024-11-13 09:13 UTC, Hyzual commented on languages/en/user-guide/project-admin.rst
> +The Cross-Tracker Search widget has a second mode called "Default mode" that allows you to select a list of trackers coming from different projects and to filter artifacts from those trackers accordi
Done

2024-11-13 09:14 UTC, Hyzual commented on languages/en/user-guide/project-admin.rst
> +If you can't read all trackers or all columns needed by the query, an error message will be displayed.
Since the selection of trackers is done with TQL FROM, I prefer to explain this in the TQL part. Done.

2024-11-13 09:24 UTC, Hyzual commented on languages/en/user-guide/project-admin.rst
> +After selecting trackers and/or entering a query, you will be able to Save the report. Once saved, all users who can access this dashboard will see the widget with your saved tracker selection and qu
It exists at L316

2024-11-13 09:24 UTC, Hyzual commented on languages/en/images/screenshots/widget/crosstracker-widget.png
I used https://squoosh.app/ with OxiPNG setting. I tried to reinstall Crush but it makes me compile pngquant which requires a Rust toolchain, and after trying unsuccessfully for 20 minutes, I gave up.

2024-11-13 09:24 UTC, Hyzual commented on languages/en/user-guide/project-admin.rst
> +You can optionally write a query using :ref:`Tuleap Query Language <xts_default_mode>` If you don't write a query, it will by default search all "Open" artifacts in the selected projects. If you use
Do you have a suggestion for making it less confusing ?

2024-11-13 10:52 UTC, Hyzual commented on languages/en/user-guide/project-admin.rst
> +You can optionally write a query using :ref:`Tuleap Query Language <xts_default_mode>` If you don't write a query, it will by default search all "Open" artifacts in the selected projects. If you use
Done, thanks

2024-11-13 13:13 UTC, Gashmob approved these changes
Wait for review of @robinsoc

2024-11-14 08:44 UTC, robinsoc approved these changes

2024-11-14 08:44 UTC, merged