Renew ansible-tuleap documentation
Enalean/tuleap-documentation-en pull request #512
Opened 2020-10-30 17:04 UTC by tcottier-enalean

I updated the ansible role to install Tuleap, and the documentation needs a refresh

2020-11-02 08:33 UTC, LeSuisse requested changes

2020-11-02 08:33 UTC, LeSuisse commented on languages/en/installation-guide/ansible-installation.rst
> +Get the ansible role from github: https://github.com/Enalean/ansible-tuleap
```suggestion
Get the Ansible role from GitHub: https://github.com/Enalean/ansible-tuleap
```

2020-11-02 08:33 UTC, LeSuisse commented on languages/en/installation-guide/ansible-installation.rst
> +        - role: ansible-tuleap
Should not this be the path to the role we downloaded from GitHub instead of just the name of the role?
BTW do we have a reason to not publish it to Ansible Galaxy? It might be easier and more in line with what the rest of the Ansible community seems to do.

2020-11-02 08:33 UTC, LeSuisse commented on languages/en/installation-guide/ansible-installation.rst
> +        tuleap_generate_le_cert: True
This variable is not not documented upstream and is not taken into account at all (see Enalean/ansible-tuleap#15), maybe we should fix it first?

2020-11-02 12:45 UTC, tcottier-enalean commented on languages/en/installation-guide/ansible-installation.rst
> +        tuleap_generate_le_cert: True
I merged your PR, it was a mistake on my side.

2020-11-02 12:58 UTC, tcottier-enalean commented on languages/en/installation-guide/ansible-installation.rst
> +        - role: ansible-tuleap
I still not have figured out on how to import a role from  the Enalean organization in Ansible Galaxy (without forking it on my own repository). I propose to let it this way for now and will try to solve this later.

2020-11-02 14:08 UTC, LeSuisse commented on languages/en/installation-guide/ansible-installation.rst
> +        - role: ansible-tuleap
>  I propose to let it this way for now and will try to solve this later.

Keeping it as this might not be the right solution because it will not work out of the box and people might not understand why. How about something like that, to force users to update it:
```suggestion
# On the next line, replace the path by the path were you retrieved the role and uncomment it
#        - role: /path/to/ansible-tuleap/role
```

2020-11-04 09:01 UTC, LeSuisse approved these changes

2020-11-04 09:01 UTC, merged