Update screenshots
Enalean/tuleap-documentation-en pull request #536
Opened 2020-11-23 15:38 UTC by sandrae

2020-12-16 14:04 UTC, romainlorentz commented on languages/en/user-guide/trackers/usage/submit-artifact.rst
> +.. figure:: ../../../images/screenshots/tracker/submit-new-artifact-en.png
The screenshot doesn't correspond with the action describe

2021-01-07 16:42 UTC, LeSuisse requested changes

2021-01-07 16:42 UTC, LeSuisse commented on languages/en/user-guide/my-personal-dashboard.rst
> -.. figure:: ../images/screenshots/user-dashboards.png
This contribution seems to add new screenshots but does not remove the old ones. Is it expected?

2022-11-21 14:12 UTC, vaceletm commented
Too old to be still relevant

2022-11-21 14:12 UTC, closed without merging