Add GitLab section
Enalean/tuleap-documentation-en pull request #546
Opened 2020-12-07 14:21 UTC by BenB-enalean

2020-12-08 08:24 UTC, yannis-rossetto requested changes

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +  This plugin is under construction, the doc and the plugin can be change.
Please use full words: "the documentation and the plugin features can change."

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +  * If you have already a reference project named ``gitlab_commit``:
I would suggest: "If you already have a project reference named ..."

You can also add a link to the reference section of the documentation.

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +You need to install Git and GitLab plugin.
I suggest: "... to install both Git and GitLab plugins"

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +
There is another limitation : 

* 2 repositories with the same name + path from 2 different GitLab instances cannot be integrated in the same project.

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +An integration allows to reference a GitLab commit in atifact Tuleap artifact in the message of a commit of the integrated GitLab repository.
Maybe this have to be moved in the reference section?

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +When you click on this reference, you will redirect to the commit with the sha1 ``<sha1>``.
I suggest: ".... to the commit with the sha1 ``<sha1>``in the GitLab instance."

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +When you click on this reference, you will redirect to the commit with the sha1 ``<sha1>``.
I suggest: ".... to the commit with the sha1 <sha1>in the GitLab instance."

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +* GitLab API token
Please precise here that this token must have at least the API access.

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +Go to the Tuleap project where you want integrate GitLab repository.
"you want to integrate"

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +When you click on, a modal opens and ask you your GitLab instance URL and GitLab API token.
"asks"

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +At this moment, the integration is deleted. All your created references can't be user anymore.
I think you wanted to say "used" instead of "user"

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +If you referenced an artifact in this repository, no Cross References will be created.
I don't understand this last sentence. Maybe you wanted to say that after removing an integration, any GitLab commit with TULEAP-{:id} will no more create cross-references?

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +.. _version-control-with-gitlab:
Maybe we have to say somewhere that the integration of a GitLab repository will add a "post push" webhook on GitLab side?

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/tuleap-entreprise.rst
> +* :ref:`GitLab <version-control-with-gitlab>`.
I suggest to say "GitLab Integration" instead of "GitLab"

2020-12-08 08:24 UTC, yannis-rossetto commented on languages/en/user-guide/code-versioning/gitlab.rst
> +.. figure:: ../../images/screenshots/gitlab/tile-gitlab.png
Thanks for the screenshots :+1:

2020-12-08 10:04 UTC, BenB-enalean commented on languages/en/user-guide/code-versioning/gitlab.rst
> +  * If you have already a reference project named ``gitlab_commit``:
A link already exists in part 'References'

2020-12-15 12:17 UTC, vaceletm requested changes

2020-12-15 12:17 UTC, vaceletm commented on languages/en/user-guide/code-versioning/gitlab.rst
> +If this webhook changes, we cannot ensure the good behavior of the plugin.
What does that mean ?

2020-12-15 12:17 UTC, vaceletm commented on languages/en/user-guide/code-versioning/gitlab.rst
> +Your GitLab API token scope must contain at least "api".
Maybe add a gitlab screenshot to make it clear it's done on GL ?

2020-12-15 12:17 UTC, vaceletm commented on languages/en/user-guide/code-versioning/gitlab.rst
> +.. note::
Note is not necessary

2020-12-15 12:17 UTC, vaceletm commented on languages/en/user-guide/code-versioning/gitlab.rst
> +How to use it
The "How to use it" miss the point in the current form. It presents how it works, not how people are supposed to use it.

It needs an "overview" that explains a typical scenario the integration solves:
- An existing gitlab instance where devs are happing
- The team want to keep using gitlab for development but want to leverage Tuleap tracking capabilities (advanced issue tracking, agile project management, etc).

The integration will allow developers to reference Tuleap artifacts from within the gitlab commit messages to ease tracability between plan & code.

2020-12-15 12:17 UTC, vaceletm commented on languages/en/user-guide/code-versioning/gitlab.rst
> +References
This section should focus on the primary use case ie Gitlab -> Tuleap "automatically".

The fact that one can build gitlab_commit xref by hand is unlikely to be the main usage hence it should not be put in first.

2020-12-15 12:17 UTC, vaceletm commented on languages/en/user-guide/code-versioning/gitlab.rst
> +Reference in another project:
No need to make a full section of this. It's built-in with references, nothing specific here

2020-12-16 07:56 UTC, BenB-enalean commented on languages/en/user-guide/code-versioning/gitlab.rst
> +If this webhook changes, we cannot ensure the good behavior of the plugin.
I wanted to say that if admin change parameters of the webhook (url, event, or anything else), we cannot ensure that cross reference will be created automatically

2020-12-18 09:11 UTC, merged