Update dev guide "Build your own internal JS lib" to use Vite
Enalean/tuleap-documentation-en pull request #645
Opened 2021-02-19 14:45 UTC by LeSuisse

2021-02-19 14:46 UTC, LeSuisse commented
Not quite sure this is ready for prime time yet until we migrated the listpicker lib so we have to show how the loading of PO files in this context.

2021-02-19 15:07 UTC, Hyzual requested changes

2021-02-19 15:07 UTC, Hyzual commented on languages/en/developer-guide/front-end/internal-libs.rst
> +        "watch:types": "rm -rf types/ && $npm_package_config_bin/tsc -w --preserveWatchOutput",
For some reason I can't comment on unmodified lines. Could you please also change L145
webpack => vite. Possibly we should add `run-p` package to the sentence.

2021-02-19 15:07 UTC, Hyzual commented on languages/en/developer-guide/front-end/internal-libs.rst
> +    types/
(Again unrelated to this line) We should also add an example of `index.ts` file showing the import line for the CSS. Since it is not in the "entrypoint" of Vite config, we need to import it in `index.ts`

```typescript
// tuleap/plugins/my-plugin/scripts/lib/my-lib-name/src/index.ts
import "../themes/style.scss";
```

2021-02-19 15:07 UTC, Hyzual commented on languages/en/developer-guide/front-end/internal-libs.rst
> +Add a ``.gitignore`` file to remove the ``dist/`` and ``types`` folders from source control.
(Again unrelated to this line) Please also change the `tsconfig.json` example above (L165-173). We need to add the "exclude" for types and change the `"outDir"` to `"types/"`

Hopefully the `emitOnlyDeclarations` can be integrated in the parent once all libs use Vite. I think we can omit it in the doc... Or maybe we should document it and remove it later once it's actually done ? What do you think about it ?

2021-02-19 17:16 UTC, LeSuisse commented on languages/en/developer-guide/front-end/internal-libs.rst
> +Add a ``.gitignore`` file to remove the ``dist/`` and ``types`` folders from source control.
I documented `emitOnlyDeclarations` just to avoid confusions, this way in the worst case case scenario we end up with an unused settings in the config file

2021-02-22 10:52 UTC, Hyzual approved these changes

2021-02-22 10:52 UTC, Hyzual commented on languages/en/developer-guide/front-end/internal-libs.rst
> +Add a ``.gitignore`` file to remove the ``dist/`` and ``types`` folders from source control.
:+1:

2021-02-22 11:05 UTC, merged