Re-organise User pages in user guide
Enalean/tuleap-documentation-en pull request #707
Opened 2021-04-13 08:03 UTC by vaceletm

This aims to have a more modern organisation
(who's talking about Citizen in a tool in 2021...)

Plus this gives dedicated pages to reference instead
of anchors.

2021-04-14 12:42 UTC, nterray requested changes

2021-04-14 12:42 UTC, nterray commented on languages/en/user-guide/user/dashboard.rst
[opt] IMHO this section lacks an introductory paragraph explaining what is the purpose of dashboards.

2021-04-14 12:42 UTC, nterray commented on languages/en/user-guide/citizen.rst
> +.. toctree::
Thanks for the split :+1:

2021-04-14 12:42 UTC, nterray commented on languages/en/user-guide/citizen.rst
> +   user/markdown
I don't think that Markdown fit well within "User guide / User" section. What do you think about a dedicated section "User guide / Writing on Tuleap". This section would explain: cross references, Markdown format, @ mentions, …

2021-04-14 12:47 UTC, vaceletm commented on languages/en/user-guide/user/create-account.rst
> +As suggested above, the first thing to do for newcomers is to create their own account
It's not my war. I was here to split the things not to rewrite the legacy.

2021-04-14 12:48 UTC, vaceletm commented on languages/en/user-guide/user/create-account.rst
> +Registering on Tuleap is quick and easy:
It's not my war. I was here to split the things not to rewrite the legacy. I can be done in a future contribution.

2021-04-14 12:49 UTC, vaceletm commented on languages/en/user-guide/user/preferences.rst
> +clicking on the "cog" image near your user name.
It's not my war. I was here to split the things not to rewrite the legacy. I can be done in a future contribution.

2021-04-14 12:49 UTC, vaceletm commented on languages/en/user-guide/user/dashboard.rst
It's not my war. I was here to split the things not to rewrite the legacy. I can be done in a future contribution.

2021-04-14 12:49 UTC, vaceletm commented on languages/en/user-guide/citizen.rst
> +   user/markdown
I copied the structure I saw in GitLab documentation but your proposal sounds good, I'll give it a try

2021-04-14 13:49 UTC, nterray commented on languages/en/user-guide/user/create-account.rst
> +As suggested above, the first thing to do for newcomers is to create their own account
> It's not my war.

Yes it is. The sentence becomes wrong because of this contribution.

2021-04-14 13:51 UTC, nterray commented on languages/en/user-guide/user/create-account.rst
> +As suggested above, the first thing to do for newcomers is to create their own account
Hmmm after checking against current version of the doc it is already broken on master. Sorry for that.
This can be done in dedicated contribution.

2021-04-14 13:52 UTC, nterray commented on languages/en/user-guide/user/preferences.rst
> +clicking on the "cog" image near your user name.
ok

2021-04-14 13:52 UTC, nterray commented on languages/en/user-guide/user/dashboard.rst
ok

2021-04-14 13:53 UTC, vaceletm commented on languages/en/user-guide/user/create-account.rst
> +As suggested above, the first thing to do for newcomers is to create their own account
At this point I would suggest to :fire: the whole page that is pointless. WDT ?

2021-04-15 07:04 UTC, nterray commented on languages/en/user-guide/citizen.rst
> +   user/markdown
Thanks :+1:

2021-04-15 07:36 UTC, nterray requested changes

2021-04-15 07:36 UTC, nterray commented on languages/en/user-guide/writing-in-tuleap.rst
> +This section covers the general rules of that applies wherever you can write text in Tuleap.
The "of that applies" seems weird.

Furthermore, I may be nitpicking, but it does not apply exactly wherever we can write text in Tuleap, for example in massmail I cannot use cross references or @ mentions.

2021-04-15 07:36 UTC, nterray commented on languages/en/user-guide/writing-in-tuleap.rst
> +auto completer to select a user.
The auto completer is proposed only on a limited set of pages.

2021-04-15 07:36 UTC, nterray commented on languages/en/user-guide/writing-in-tuleap.rst
> +
What do you think about explaining that the mention is a link to the user profile page?

2021-04-15 07:36 UTC, nterray commented on languages/en/user-guide/writing-in-tuleap.rst
> +Resources
Since this paragraph does not concern references or mentions, I suggest to move it inside the Markdown section.

2021-04-15 07:54 UTC, vaceletm commented on languages/en/user-guide/writing-in-tuleap.rst
> +This section covers the general rules of that applies wherever you can write text in Tuleap.
It's you that asked me to write a section that applies to the whole tuleap texts ;)
You know better than me that there is no such thing and **nothing** applies consistently on all text area.

So I don't know what to write

2021-04-15 07:54 UTC, vaceletm commented on languages/en/user-guide/writing-in-tuleap.rst
> +auto completer to select a user.
I don't even know where it applies, I cannot add this information

2021-04-15 09:29 UTC, nterray commented on languages/en/user-guide/writing-in-tuleap.rst
> +This section covers the general rules of that applies wherever you can write text in Tuleap.
> You know better than me that there is no such thing and nothing applies consistently on all text area.

Yes, that's why we should not be such assertive. Proposal: 

```
This section covers the general rules on writing text in Tuleap.
```

What do you think?

2021-04-15 09:36 UTC, nterray commented on languages/en/user-guide/writing-in-tuleap.rst
> +auto completer to select a user.
> I don't even know where it applies

Neither do I :sweat: 

Proposal: 
* Use the first rule of the autocompleter: you don't talk about the autocompleter
* Or be less assertive. Something like:
  ```diff
  - […], after 3 characters Tuleap will propose an
  + […]. In some areas, after 3 characters Tuleap will propose an
  ```

2021-04-15 09:37 UTC, nterray commented on languages/en/user-guide/writing-in-tuleap.rst
> +Resources
I agree with the removal :+1:

2021-04-15 12:08 UTC, vaceletm commented on languages/en/user-guide/writing-in-tuleap.rst
> +This section covers the general rules of that applies wherever you can write text in Tuleap.
Ok

2021-04-15 12:09 UTC, vaceletm commented on languages/en/user-guide/writing-in-tuleap.rst
> +auto completer to select a user.
OK

2021-04-15 17:07 UTC, nterray approved these changes

2021-04-15 17:07 UTC, merged