First bites of Program Management documentation
Enalean/tuleap-documentation-en pull request #800
Opened 2021-09-07 09:09 UTC by vaceletm

Introduction plus SAFe templates

2021-09-10 16:02 UTC, nterray requested changes

2021-09-13 07:49 UTC, vaceletm commented on languages/en/user-guide/program-management.rst
> +A milestone is a tracker that will define a period of time something is worked on. It should have the following `semantics <tracker-semantic>`_:
Reworded to avoid the question :)

2021-09-13 07:50 UTC, vaceletm commented on languages/en/user-guide/tuleap-entreprise.rst
> -* :ref:`Roadmap <roadmap>`.
Good catch :kiss:

2021-09-13 12:37 UTC, nterray approved these changes

2021-09-13 12:37 UTC, merged